import React from 'react'
import { StyleSheet, Text, SafeAreaView, ScrollView } from 'react-native'

export default function TermsOfUseScreen ({ navigation, props, route }) {
  return (

    <SafeAreaView style={styles.container}>
      <ScrollView style={styles.scrollView}>
        <Text style={{textAlign: 'center', fontSize: 30, textDecorationLine: 'underline', margin: 10}}>
        Terms Of Use
      </Text>

      <Text style={{ textAlign: 'left', fontSize: 16, margin: 10}}>
          PLEASE READ THESE TERMS OF USE CAREFULLY BEFORE USING THIS APP OR WEBSITE AS THEY CONTAIN IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, REMEDIES AND OBLIGATIONS. THESE INCLUDE VARIOUS LIMITATIONS AND EXCLUSIONS, AND A DISPUTE RESOLUTION CLAUSE THAT GOVERNS HOW DISPUTES WILL BE RESOLVED.{"\n"}{"\n"}

          Bama   is intended to be a tool to assist in the medical care of patients and is not a substitute for professional medical care. Every effort has been made to ensure the accuracy of the content; however, accuracy cannot be guaranteed. The app is a guide and not a substitute for proper medical training or sound clinical judgement and does not set the standard of care. The content was designed for use by current best medical evidence guidelines available in the United  es. Drug dosages, treatment algorithms, and general medical practice may vary in other countries. It is the responsibility of the user to confirm the accuracy of all content. The user is advised to consult additional references before making any clinical decisions. Before administration of any drug, it is recommended to review manufacturerâ€™s current product information for accepted indications, dosages, adverse effects, contraindications, and any other information pertinent to appropriate use. The developer assumes no responsibility for any loss, injury, and/or damage to persons or property arising from or related to the use of Bama  . By using this application, the user assumes liability for and shall indemnify, defend, protect, save, and hold harmless Bama   / James M Kempema, MD PA from and against any and all liabilities, claims, demands, suits, judgements, damages, and losses (including all costs, fees, and expenses in connection therewith or incidental thereto), for death of, or injury or harm to, any person whomsoever, and for loss of, damage to , or destruction of any property whatsoever, including any loss of use thereof.{"\n"}{"\n"}

          Upon acceptance of these terms of use (the “Terms of Use”), together with the Bama Privacy Policy (the “Privacy Policy”), you the user of this app and website (“you” and/or “user”) signify that you have read, understand and agree to be bound by the Terms of Use and the Privacy Policy, and that combined, the Terms of Use and the Privacy Policy will form a binding agreement (the “Agreement”) between you and Bama. The Agreement governs your use of Bama  , including all content such as text, information, discussion forums, and all information made available to you or by you through the apps by Bama and/or third parties. The Agreement supersedes any prior agreements between you and Bama relating to your use of the apps or websites. Unless otherwise specified, the terms “includes”, “including”, “e.g.,”, “for example”, and other similar terms are deemed to include the term “without limitation” immediately thereafter.{"\n"}{"\n"}

          Bama reserves the right at our sole discretion, to change, modify, add, or delete all or portions of this Agreement at any time and, as such, we ask that you periodically visit this page. In the event that significant changes are made, Bama commits to advising all users at the time that any significant change is made. By continuing to use the apps and sites you agree to be bound by any such revisions and, therefore, it is your responsibility to regularly revisit this Agreement and to review the current terms.
          Bama is willing to grant access to this software only to those who accept all the terms and conditions of this license agreement. If you do not agree to all the terms and conditions, Bama is unwilling to license and grant access to the software to you, and you should discontinue using the apps.{"\n"}{"\n"}
          
          1. Eligibility
          You are eligible to use the apps or sites if you are a student, healthcare provider, scientist or researcher. Bama reserves sole discretion to determine if an individual is eligible. You may not set up an account on behalf of another individual or entity unless you are authorized to do so. By using the apps or websites, you agree to and will abide by all of the terms and conditions of this Agreement. You must be over the age of 16 to use the apps.{"\n"}{"\n"}
          
          2. Registration & Account Security
          In consideration of your use of the apps you agree to: (a) provide accurate, current and complete information about you as may be prompted by any registration forms on the website (“Registration Data”); (b) maintain the security of your password and identification; (c) maintain and promptly update the Registration Data, and any other information you provide to Bama, to keep it accurate, current and complete; and (d) be fully responsible for all use of your account and for any and all actions that take place using your account.{"\n"}{"\n"}
          
          3. Copyright
          All content on the apps and websites including designs, text, graphics, pictures, information, applications, software, sound and other files, and their selection and arrangement (the “Site Content”) are the sole proprietary property of Bama unless otherwise indicated. You do not have the right to modify, copy, perform, distribute, frame, reproduce, republish, upload, download, scrape, display, post, transmit, or sell in any form or by any means, in whole or in part, except that the foregoing does not apply to your own User Content (as defined below) that you legally post on the apps or websites, of any of the Site Content without Bama’s prior written consent as they are protected under applicable copyright laws and treaty provisions (including but not limited to applicable intellectual property laws).
          We respect the intellectual property rights of others and we prohibit users from uploading, posting or otherwise transmitting on the apps or websites any materials that violate another party’s intellectual property rights. When we receive proper written notification of alleged copyright infringement, we will promptly remove or disable access to the allegedly infringing material. If you believe that any material on the website infringes upon any copyright which you own or control, you may send a written notification of such infringement to Bama at 1benjamin.mati@gmail.com{"\n"}{"\n"}
          
          4. User License
          Provided that you are eligible for use of the apps or websites, Bama hereby grants you a limited license to access and use the apps and the Site Content solely for your personal, non-commercial use. Except for your own User Content (as defined below), you may not upload or republish Site Content on any internet, intranet or extranet site or incorporate the information in any other database or compilation, and any other use of the Site Content is strictly prohibited. Such license is subject to these Terms of Use and does not permit use of any data mining, robots, scraping or similar data gathering or extraction methods. Any use of the apps or the Site Content other than as specifically authorized herein, without the prior written permission of Bama, is strictly prohibited and will terminate the license granted. Such unauthorized use may also violate applicable laws including copyright and trademark laws and applicable communications regulations and  utes. Unless explicitly  ed herein, nothing in these Terms of Use shall be construed as conferring any license to intellectual property rights, whether by estoppel, implication or otherwise. This license is revocable at any time without notice and with or without cause. All rights not expressly granted to you are reserved by Bama.{"\n"}{"\n"}
          
          5. User Conduct
          You are responsible for all activity occurring through your account and you represent that you shall abide by all applicable local, provincial/ e, national and foreign laws, treaties and regulations in connection with the use of the apps and sites, including those related to data privacy, intellectual property, copyright, international communications and the transmission of technical or personal data. In the event that you suspect a breach of security, including without limitation any unauthorized access of your account, you will notify Bama as soon as possible.
          You may not access the apps or sites for any benchmarking or competitive purposes such as monitoring its availability, performance or functionality. You may not resell, redistribute, or put to any commercial use, any content or information from this app or site.{"\n"}{"\n"}

          You represent, warrant and agree that no materials of any kind submitted through your account or otherwise posted, transmitted, or shared by you on or through the apps or websites will violate or infringe upon the rights of any third party, including copyright, trademark, privacy, publicity or other personal or proprietary rights; or contain libelous, defamatory or otherwise unlawful material.
          In addition, without limitation, you agree not to use the app or website to:
          harvest or collect email addresses or other contact information of other users from the website by electronic or other means for the purposes of sending unsolicited emails or other unsolicited communications;
          use the app or website in any unlawful manner or in any other manner that could damage, disable, overburden or impair the website; use automated scripts to collect information from or otherwise interact with the website;
          upload, post, transmit, share, store or otherwise make available any content that we deem to be harmful, threatening, unlawful, defamatory, infringing, abusive, inflammatory, harassing, vulgar, obscene, fraudulent, invasive of privacy or publicity rights, hateful, or racially, ethnically or otherwise objectionable;
          register for more than one account, register for an account on behalf of an individual other than yourself, or register for an account on behalf of any group or entity;
          impersonate any person or entity, or falsely  e or otherwise misrepresent yourself, your age or your affiliation with any person or entity; upload, post, transmit, share or otherwise make available any unsolicited or unauthorized advertising, solicitations, promotional materials, “junk mail,” “spam,” “chain letters,” “pyramid schemes,” or any other form of solicitation; upload, post, transmit, share, store or otherwise make publicly available any private information of any third party, including, addresses, phone numbers, email addresses, social security numbers and credit card numbers;
          solicit personal information or solicit passwords or personally identifying information for commercial or unlawful purposes;
          intimidate or harass another;
          upload, post, transmit, share, store or otherwise make available content that would constitute, encourage or provide instructions for a criminal offense, violate the rights of any party, or that would otherwise create liability or violate any local,  e, national or international law;
          use or attempt to use another’s account, service or system, or create a false identity on the app or website; or
          upload, post, transmit, share, store or otherwise make available content that, in the sole judgment of Company, is objectionable or which restricts or inhibits any other person from using or enjoying the Site, or which may expose Bama or its users to any harm or liability of any type.{"\n"}{"\n"}
          
          6. User Content Posted On The Website
          You are solely responsible for the profiles (including your name, image, and likeness), messages, notes, text, information, and other content that you upload, publish or display (hereinafter, “post”) on or through the app or website, or transmit to or share with other users (collectively the “User Content”). You may not post, transmit, or share User Content on the website that you did not create or that you do not have permission to post. You understand and agree that Bama may, but is not obligated to, review the app or website and may delete or remove (without notice) any Site Content or User Content in its sole discretion, for any reason or no reason, including User Content that in the sole judgment of Bama violates this Agreement, or which might be offensive, illegal, or that might violate the rights, harm, or threaten the safety of users or others. You are solely responsible at your sole cost and expense for creating backup copies and replacing any User Content you post or store on the app or website or provide to Bama.
          When you post User Content to the app or website, you authorize and direct us to make such copies thereof as we deem necessary in order to facilitate the posting and storage of the User Content on the website. By posting User Content to any part of the website, you automatically grant, and you represent and warrant that you have the right to grant, to Bama an irrevocable, perpetual, non-exclusive, transferable, fully paid, worldwide license (with the right to sublicense) to use, copy, publicly perform, publicly display, reformat, translate, excerpt (in whole or in part) and distribute such User Content for any purpose, commercial, advertising, or otherwise, on or in connection with the website or the promotion thereof, to prepare derivative works of, or incorporate into other works, such User Content, and to grant and authorize sublicenses of the foregoing. You may remove your User Content from the Site at any time. If you choose to remove your User Content, the license granted above will automatically expire, however you acknowledge that the Company may retain archived copies of your User Content. Bama does not assert any ownership over your User Content; rather, as between us and you, subject to the rights granted to us in this Agreement, you retain full ownership of all of your User Content and any intellectual property rights or other proprietary rights associated with your User Content.{"\n"}{"\n"}
          
          7. Third Party Content
          There is certain content available on the site from third parties, including other users, that Bama has no editorial control over. Any advice,  ements, services, offers or other information or content expressed or made available by third parties, including other users, are those of the respective individual or company and not of Bama. Bama is not responsible or liable in any manner for any third party content posted on the app or website or in connection with the website, whether posted or caused by users of the website, by Bama, by third parties or by any of the equipment or programming associated with or utilized in the website. Bama is not responsible for the conduct, whether online or offline, of any user of the app or website. As such, it is your responsibility to evaluate any content available on the site for accuracy, reliability, completeness or usefulness.
          The apps and websites will post links to published articles from the medical literature as well as clinical decision support tools (“Content”). Inclusion of a link does not imply approval or endorsement of the linked Content and Bama is not responsible for the content, accuracy or opinions expressed in such content. If you decide to access this third-party content, you do so at your own risk. We do not warranty or guarantee the accuracy, completeness, adequacy or currency of the Content. Your use of the Content on this app or site or of any Content linked to from, or otherwise made available through, this app or site (including without limitation any content or other materials accessed through a publisher website, “open access” website, or other third party source) is at your own risk, and no license or right is granted with respect to any such materials.{"\n"}{"\n"}
          
          8. Intellectual Property Rights
          Nothing in these Terms of Use should be construed as conferring upon you any copyright or other intellectual property license or right (whether by implication, estoppel or otherwise), unless we have expressly said so. You agree that the Content , the apps and the sites are protected by applicable copyrights, trademarks, service marks, patents or other proprietary rights and laws, all of which belong to Bama, its licensors or the applicable rights holders of the particular materials. Without limiting the foregoing, you acknowledge and agree that nothing in these Terms of Use confers upon you any right or license to access, copy, distribute or otherwise use any content or materials accessed by you through the site, and you (and your employer or affiliated institution, as applicable) are solely responsible (and Bama therefore has no responsibility) to obtain any permission that may be required for any use made by you (or by your employer or affiliated institution) of such content.{"\n"}{"\n"}
          
          9. Indemnification
          You agree to indemnify and hold Bama and its parent organizations, subsidiaries and affiliates, and each of their directors, officers, agents, consultants, contractors, partners, employees, suppliers and sponsors, harmless from and against any loss, liability, claim, demand, damages, costs and expenses, including reasonable attorney’s fees, arising out of or in connection with: (a) any claim arising out of or relating to your use of the apps, sites or content provided by you, including without limitation any claim alleging that use of this content infringes or misappropriates the rights of, or has caused harm to, a third party; or (b) any claim arising from the breach or violation by you of any responsibilities, representation, covenants or warranties under this Agreement or of any law or the rights of any third party.{"\n"}{"\n"}
          
          10. Disclaimer of Warranties and Limits of Liability
          All conditions, representation and warranties, whether express, implied,  utory or otherwise, including without limitation any implied warranty of suitability for a particular purpose or non-infringement of third party rights, are hereby disclaimed to the maximum extent permitted by applicable law by Bama.
          Bama AND ITS PARENT ORGANIZATIONS, SUBSIDIARIES AND AFFILIATES, AND EACH OF THEIR DIRECTORS, OFFICERS, AGENTS, CONSULTANTS, CONTRACTORS, PARTNERS, EMPLOYEES, SUPPLIERS AND SPONSORS DO NOT REPRESENT OR WARRANT THAT SOFTWARE, CONTENT OR MATERIALS ON THE APPS OR WEBSITES ARE ACCURATE, COMPLETE, RELIABLE, CURRENT OR ERROR-FREE OR THAT THE APPS, WEBSITES OR ITS SERVERS, OR ANY PLATFORM APPLICATIONS ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. THE APPS, WEBSITES AND ALL CONTENT ARE PROVIDED TO YOU STRICTLY ON AN “AS IS” BASIS. THEREFORE, YOU SHOULD EXERCISE CAUTION IN THE USE AND DOWNLOADING OF ANY SUCH SOFTWARE, CONTENT OR MATERIALS AND USE INDUSTRY-RECOGNIZED SOFTWARE TO DETECT AND DISINFECT VIRUSES. WITHOUT LIMITING THE FOREGOING, YOU UNDERSTAND AND AGREE THAT YOU DOWNLOAD OR OTHERWISE OBTAIN CONTENT, MATERIAL, DATA OR SOFTWARE FROM OR THROUGH THE APPS OR WEBSITES AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR YOUR USE THEREOF AND ANY INJURY OR DAMAGE TO YOUR OR TO ANY PERSON’S COMPUTER, OR OTHER HARDWARE OR SOFTWARE, RELATED TO OR RESULTING FROM USING OR DOWNLOADING MATERIALS IN CONNECTION WITH THE WEBSITE, THEFT OR DESTRUCTION OR UNAUTHORIZED ACCESS TO, OR ALTERATION OF THE WEBSITE, LOSS OF DATA OR OTHER HARM OF ANY KIND THAT MAY RESULT. THE WEBSITE MAY BE TEMPORARILY UNAVAILABLE FROM TIME TO TIME FOR MAINTENANCE OR OTHER REASONS.
          IN NO EVENT SHALL Bama AND ITS PARENT ORGANIZATIONS, SUBSIDIARIES AND AFFILIATES, AND EACH OF THEIR DIRECTORS, OFFICERS, AGENTS, CONSULTANTS, CONTRACTORS, PARTNERS, EMPLOYEES, SUPPLIERS AND SPONSORS BE LIABLE TO YOU OR ANY THIRD PERSON FOR ANY INDIRECT, CONSEQUENTIAL, PUNITIVE, SPECIAL, INCIDENTAL OR EXEMPLARY DAMAGES OF ANY TYPE OR KIND, INCLUDING LOSS OF DATA, REVENUE, PROFITS, OR OTHER ECONOMIC ADVANTAGE, ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE SITE, INCLUDING FOR ANY CONTENT OBTAINED THROUGH THE SERVICE, ANY ERROR, OMISSION, INTERRUPTION, DELETION, INACCURACY, DEFECT, DELAY IN OPERATION OR TRANSMISSION, COMMUNICATIONS LINE FAILURE, TECHNICAL MALFUNCTION OR OTHER PROBLEMS OF ANY TELEPHONE NETWORK OR SERVICE, COMPUTER SYSTEMS, SERVERS OR PROVIDERS, COMPUTER EQUIPMENT, SOFTWARE, FAILURE OR EMAIL OR PLAYERS ON ACCOUNT OF TECHNICAL PROBLEMS OR TRAFFIC CONGESTION ON THE INTERNET OR AT THE WEBSITE OR COMBINATION THEREOF, EVEN IF Bama HAS BEEN PREVIOUSLY ADVISED OF SUCH DAMAGES OR HAS BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. UNDER NO CIRCUMSTANCES WILL Bama BE RESPONSIBLE FOR ANY LOSS OR DAMAGE, INCLUDING ANY LOSS OR DAMAGE TO ANY USER CONTENT OR PERSONAL INJURY OR DEATH, RESULTING FROM ANYONE’S USE OF THE APP, WEBSITE OR ANY USER CONTENT POSTED ON OR THROUGH THE WEBSITE OR TRANSMITTED TO USERS, OR ANY INTERACTION BETWEEN USERS OF THE APP OR WEBSITE, WHETHER ONLINE OR OFFLINE EVEN IF Bama HAS BEEN PREVIOUSLY ADVISED OF SUCH DAMAGES OR HAS BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
          Reference to any products, services, processes or other information, by trade name, trademark, manufacturer, supplier or otherwise does not constitute or imply endorsement, sponsorship or recommendation thereof, or any affiliation therewith, by Bama.{"\n"}{"\n"}
          
          11. Arbitration
          If, at any time during the currency of this agreement, any dispute, difference or question shall arise between the parties touching matters not specifically provided for herein, or any issue shall arise touching the construction, meaning or effect of this agreement, or anything herein contained, or the rights or liabilities of the parties to this agreement, then every such dispute, difference or question shall be referred to a single arbitrator, if the parties can agree upon one within seven (7) days of you or Bama referring the matter to arbitration. Otherwise, the matter shall be referred to a board of three (3) arbitrators, one (1) to be appointed by you, one (1) to be appointed by Bama, and the third to be appointed by the first two (2) named arbitrators, in writing, before they enter upon the business of the reference. If either party shall refuse or neglect to appoint an arbitrator within fifteen (15) days after the other has appointed an arbitrator and has served a written notice upon the other party requiring such party to make such appointment, then the arbitrator first appointed shall, at the request of the person appointing him, proceed to hear and determine the matter at issue as if he or she were a single arbitrator appointed by all parties for that purpose. The award or determination which shall be made by the arbitrator, arbitrators or majority of them shall be absolutely final and binding upon the parties. In the event that the first two (2) named arbitrators are unable to agree upon a third within seven (7) days after the appointment of the last of them, then, upon the motion of either arbitrator to any Judge of the Provincial Court of British Columbia, such Judge shall be entitled to name the third arbitrator, whose appointment shall be final and binding upon the parties. In all respects, subject to the terms of this agreement, the Commercial Arbitration Act of British Columbia and amendments thereto shall govern such proceedings and the arbitrators shall be entitled to fix and apportion liability for the costs of the arbitration.{"\n"}{"\n"}
          
          12. Termination
          Bama reserves the right at any time and in its sole discretion to revoke a user’s right to access the apps or sites and/or to close down and delete the account and/or any content or information that you have posted on the site. In the event that Bama exercises this right, it will not be required to provide notice to the affected user and will assume no liability for this action.{"\n"}{"\n"}
          
          13. Assignment
          Bama may assign this Agreement, in whole or in part, in its sole discretion. In the event that Bama chooses to assign this Agreement, we will advise the user of the same. The user shall not be entitled to assign any of the rights and benefits conferred by this Agreement.{"\n"}{"\n"}
          
          14. Waiver of Breach
          Failure by Bama to act upon a breach by you of any obligation under this Agreement shall not constitute a waiver or relinquishment for the future of such obligation, but the same shall remain in full force and effect and Bama shall continue to have the right to enforce all the terms of this Agreement on the user.{"\n"}{"\n"}
          
          15. Force Majeure
          Bama shall not be liable for any failure or unavailability of the apps or sites as a result of the loss or destruction of data, the deletion or corruption of storage media, power failures, unavailability of suppliers or any other event beyond its control.{"\n"}{"\n"}
          
          16. Invalidity
          If anyone or more of the provisions contained in the Agreement should be determined to be invalid, illegal or unenforceable in any respect, the validity, legality and enforceability of the remaining provisions of the Agreement shall not in any way be affected or impaired thereby.{"\n"}{"\n"}
          
          17. Governing Law
          This Agreement shall in all respects be governed by and be construed in accordance with the laws of the Province of British Columbia, and the applicable laws of Canada therein.{"\n"}{"\n"}
          
          18 Advertisements
          You acknowledge and agree that some of the apps or sites may be supported by advertising revenue and may contain advertisements or promotions. If you elect to have any personal, professional or business dealings with anyone whose products or services may be advertised, you acknowledge and agree that such dealings are solely between you and such advertiser and you further acknowledge and agree that Bama shall not have any responsibility or liability for any losses or damages that you may incur as a result of such dealings.{"\n"}{"\n"}
          
          19. Additional Terms
          The content provided is educational in nature and  not meant to be a substitute for professional advice and is not to be used for medical diagnosis and / or medical treatment. Medicine is an ever-changing science. As new research and clinical experience broaden out knowledge, changes in treatment and drug therapy are required. In view of the possibility of human error or changes in medical sciences, neither the author nor the developer warrant that the information contained in these apps is in every respect accurate or complete, and they are not responsible for any errors or omissions or the results obtained from the use of such information. Extensive effort has been exerted to make these apps as accurate as possible. However, the accuracy and completeness of the information provided by these apps cannot be guaranteed. This software is to be used as a guide only, and health care professionals should use sound clinical judgement and individualize therapy to each specific patient care situation. The author makes no claims whatsoever, expressed or implied, about the authenticity, accuracy, reliability, completeness or timeliness of the material, calculations, software, text, graphics and links given.{"\n"}{"\n"}
          
          20. Contacting Bama
          If you have any questions about these Terms, please contact Bama at 1benjamin.mati@gmail.com
        </Text>
      </ScrollView>
    </SafeAreaView>
  )
}

const styles = StyleSheet.create({
  container: {
    paddingTop: 10,
    marginTop: 0,
    flex: 1
  },
  title: {
    fontSize: 20,
    marginLeft: 20,
    marginRight: 10
  },
  scrollView: {
    marginHorizontal: 20,
  },
  SubmitButtonStyle: {
    marginTop: 10,
    backgroundColor: 'white',
    paddingTop: 15,
    paddingBottom: 15,
    marginLeft: 30,
    marginRight: 30,
    borderColor: '#fff',
    borderRadius: 25,
    borderWidth: 1,
    width: 300,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between'
  }
})
